Feature/#34 select next writer
JangHyeLyn/Exchange-Diary-Android pull request #36
Opened 2021-06-22 12:19 UTC by hr955

다음 작성자 선택 페이지 UI 제작

2021-06-26 06:55 UTC, AnkyoungMoo requested changes
홀리 슅,, 왜이렇게 늘었냐구~~!

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/build.gradle.kts
> +    implementation("androidx.constraintlayout:constraintlayout:2.0.4")
이거 꼭 필요한걸까..?
이미 정의되어있을꺼같은데

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.select_next_writer.SelectNextWriterActivity"></activity>
이거는 인라인에 클로즈해주는게 좋슴미당

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/NextWriterListAdapter.kt
> +class NextWriterListAdapter :
ListAdapter라는 어댑터가 따로 존재해서 RecyclerViewAdpater로 네이밍 변경하는게 헷갈리지 않을 수 있을거같아
ListAdapter라고 RecyclerViewAdpater의 데이터 개선쪽 성능이슈를 해결한 Adapter가 존재해서 이름 변경해주면 좋을듯?!
필수는 아닙니당

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +        rv_next_writer_list.addItemDecoration(SpacingRecyclerView(dpToPixel(8.toFloat())))
데이터바인딩 이용할 수 있는데 코틀린익스텐션 이용된거같은데?!
데이터바인딩으로 바꿔주셔유~

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +    }
클래스 내부에 클래스를 선언하면 중첩 클래스가 되고 static 해지는데 itemDecoration은 static한 클래스일 필요가 없어
외부에 따로 선언해주거나 파일을 새로 만들어서 클래스를 정의하는게 더 좋을거같아

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +    }
이 확장함수는 Context에 확장함수를 만드는거라 따로 파일을 만들어서 관리하는게 조금 더 좋긴해

하지만 내가 Int에 .toPx() 이라는 확장함수를 만들어놔서 이거 안만들어도 될껄..?
기능이 조금 다르면 Utils에 Context.kt 만들어서 거기에 선언해주는게 좋을꺼같아

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/src/main/res/layout/activity_select_next_writer.xml
> +        <LinearLayout
여기 LinearLayout이 꼭 필요한게 아니라면 제거하도록 하자
ConstraintLayout 안에는 레이아웃 계층이 최대한 생기지 않도록 해야해

2021-06-26 06:55 UTC, AnkyoungMoo commented on build.gradle.kts
> +    val kotlin_version by extra("1.4.21")
이거 필 없으면 제거하자

2021-06-26 06:55 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +
공백제거

2021-06-26 11:43 UTC, hr955 commented on app/build.gradle.kts
> +    implementation("androidx.constraintlayout:constraintlayout:2.0.4")
이거는 아마 업데이트같은거 누르면서 자동으로 추가된것 같습니다..😯
제거 완료

2021-06-26 11:43 UTC, hr955 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.select_next_writer.SelectNextWriterActivity"></activity>
수정 완료

2021-06-26 11:43 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/NextWriterListAdapter.kt
> +class NextWriterListAdapter :
수정 완료

2021-06-26 11:43 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +        rv_next_writer_list.addItemDecoration(SpacingRecyclerView(dpToPixel(8.toFloat())))
수정 완료

2021-06-26 11:43 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +    }
수정 완료

2021-06-26 11:44 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +    }
수정 완료

2021-06-26 11:44 UTC, hr955 commented on app/src/main/res/layout/activity_select_next_writer.xml
> +        <LinearLayout
LinearLayout 제거 완료

2021-06-26 11:45 UTC, hr955 commented on build.gradle.kts
> +    val kotlin_version by extra("1.4.21")
얘두 업데이트 누르면서2.....😅
제거 완료

2021-06-26 11:45 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SelectNextWriterActivity.kt
> +
수정 완료

2021-06-27 05:02 UTC, AnkyoungMoo approved these changes
네이밍만 변경하고 머지해도 좋을꺼같아유~

2021-06-27 05:02 UTC, AnKyungMoo commented on app/src/main/java/com/km/exchangediary/ui/select_next_writer/SpacingRecyclerView.kt
> +class SpacingRecyclerView(private val itemSpace: Float) : RecyclerView.ItemDecoration() {
ItemDecoration 이 이름에 붙는게 좋다..!

2021-06-27 05:32 UTC, leewoongi approved these changes

2021-06-28 11:05 UTC, merged