Feature/#32 diary setting UI
JangHyeLyn/Exchange-Diary-Android pull request #43
Opened 2021-07-09 13:59 UTC by hr955

내용
-----------------------
다이어리 맨 뒷장에 연결될 Diary Setting UI

추후 수정
-----------------------
RecyclerView 스크롤 효과

2021-07-13 09:40 UTC, AnkyoungMoo requested changes
리뷰 남겼으유

2021-07-13 09:40 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/diary_close/DiaryCloseActivity.kt
> +            ).show(supportFragmentManager, "tag")
"tag"를 어떤 다이얼로그인지 식별하는걸로 두는게 더 좋을꺼같아유
지금은 태그를 사용하고 있지 않지만 태그를 사용하는 케이스들이 생기면 중복 태그때문에 문제가 생길지도 모르니깐?!

2021-07-13 09:40 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeActivity.kt
> +
공백 제거

2021-07-13 09:40 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeData.kt
> +    val groupName: String
이거 현재 데이터 다 넣은게 아니라 예시로 한개만 넣어둔거지?
만약 string 하나만 쓰는게 전부라면 그냥 arrayList에 string 직접 넣는게 더 좋을꺼같은데?!

2021-07-13 09:40 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/leave_diary/LeaveDiaryActivity.kt
> +            ).show(supportFragmentManager, "tag")
여기도 태그 같은 이유

2021-07-13 09:40 UTC, AnkyoungMoo commented on app/src/main/res/drawable/radio_button_unfocused.xml
> +            <solid android:color="#00000000" />
black 쓰면 되지 않나유?

2021-07-13 09:40 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeAdapter.kt
> +    }
ViewHolder를 inner class로 정의하면 selectCheck가 접근 되면서 화면 갱신까지 가능할꺼같은데 분리하는거보다
onBind에 묶는게 좋아보입니당. 안되면 말구

inner class 를 이용하지 않는 방법도 고민해볼게유

2021-07-13 16:57 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/diary_close/DiaryCloseActivity.kt
> +            ).show(supportFragmentManager, "tag")
수정 완료

2021-07-13 16:58 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeActivity.kt
> +
수정 완료

2021-07-13 16:58 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeData.kt
> +    val groupName: String
수정 완료

2021-07-13 16:58 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/leave_diary/LeaveDiaryActivity.kt
> +            ).show(supportFragmentManager, "tag")
수정 완료

2021-07-13 16:58 UTC, hr955 commented on app/src/main/res/drawable/radio_button_unfocused.xml
> +            <solid android:color="#00000000" />
수정 완료

2021-07-13 16:58 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeAdapter.kt
> +    }
일단 수정했는데 리뷰해주신 의도대로 수정한게 맞는지 잘 모르겠어요 👀

2021-07-15 10:42 UTC, AnkyoungMoo commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeAdapter.kt
> +    }
굿굿 훌룡합니당
onBind에 position 넘기지 말고 position 대신에 bindingAdapterPosition으로 되는지 한 번 확인해보고 되면 bindingAdapterPosition 이용하고 아니면 position 이용하는걸루 가쥬

item이 groupChangeList[position] 을 넘겨받은건데 position을 또 넘기니까 이상해서..

2021-07-15 10:43 UTC, AnkyoungMoo approved these changes
우선 approve 할게유~ comment 남긴거 한 번 테스트해보고 되면 바꿔서 머지, 안되면 그냥 그대로 가주세용

2021-07-15 15:25 UTC, hr955 commented on app/src/main/java/com/km/exchangediary/ui/diary_setting/group_change/GroupChangeAdapter.kt
> +    }
수정했어요~! 머지할게요!

2021-07-15 15:25 UTC, merged